### ISSUE TITLE
cannot start openmrs

### ISSUE THREAD

**Issue by besmirzanaj** [TwistTheNeil/openmrs-automated-install#5] opened 2017-03-30 10:10 UTC
When trying to install on an Ubuntu 14.04 LTS version and trying to manually start the WAR through the Tomcat Web Application Manager I get the following error:

> FAIL - Application at context path /openmrs could not be started

to avoid this follow manually these steps:

> apt-get install software-properties-common
> apt-add-repository ppa:webupd8team/java
> apt-get update
> apt-get install oracle-java8-installer

Then list and copy the path of the java 8 sdk to be used for your tomcat 7 config:
update-java-alternatives -l

sample output can be like this:
> java-1.6.0-openjdk-amd64 1061 /usr/lib/jvm/java-1.6.0-openjdk-amd64
> java-1.7.0-openjdk-amd64 1071 /usr/lib/jvm/java-1.7.0-openjdk-amd64
> **java-8-oracle 1081 /usr/lib/jvm/java-8-oracle**

We are interested in the third line of java8. First copy the path _/usr/lib/jvm/java-8-oracle_ and place it in the JAVA_HOME section locate in the file: /etc/default/tomcat7

Your file should look like this:
> The home directory of the Java development kit (JDK). You need at least
> JDK version 1.5. If JAVA_HOME is not set, some common directories for
> OpenJDK, the Sun JDK, and various J2SE 1.5 versions are tried.
> #JAVA_HOME=/usr/lib/jvm/openjdk-6-jdk
> JAVA_HOME=/usr/lib/jvm/java-8-oracle

Don't forget to restart tomcat :
service tomcat7 restart
and then you can reach your application at
http://yourip:8080/openmrs

**Comment by TwistTheNeil** [comment] 2017-04-20 20:55
Hey, thanks for this. Unfortunately, I won't be able to push a fix for this quickly due to life stuff. If you have a patch which generalizes 14.04 and the latest ubuntu release, that would be great! If not, this will be open for a few more days/weeks until I am able again.

**Comment by TwistTheNeil** [comment] 2017-05-03 15:42
Update: I tested it on fresh install and had no issues.
Please let me know the circumstances/methods to reproduce.

**Comment by besmirzanaj** [comment] 2017-05-03 15:47
My errors consisted in the JAVA version not being able to start the application. As soon as I manually specified the JAVA version to be 8 then the app worked immediately.
The test was performed in a VPS with updated Ubuntu 14.04. Did not try yet in 16.04.

**Comment by TwistTheNeil** [comment] 2017-05-04 00:07
Ah, sorry about that, I had tested it on 16.04 (latest LTS). I would like to hear from you as to whether it makes sense to support 14.04? The init system is also different and it will be tedious to support various configurations.

You fix does work though, thank you!

**Comment by TwistTheNeil** [comment] 2017-06-11 04:10
I'm going to go ahead and close this. Going forward, I will focus on the latest LTS for ubuntu and stable debian.

**Closed as completed by TwistTheNeil** 2017-06-11 04:10 UTC
